name: build-mac

on:
  workflow_dispatch: {}         # manueller Start

jobs:
  mac:
    runs-on: macos-latest

    # run-Schritte standardmäßig in frontend/ ausführen
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Dependencies installieren
        run: npm ci

      - name: Renderer bauen (Vite, base=./ via mode desktop)
        run: npm run build:renderer

      - name: Electron main bauen (tsc)
        run: npm run build:electron

      - name: macOS ZIP bauen (unsigniert)
        run: npx electron-builder --mac zip --publish never -c electron/electron-builder.yml
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false   # Sign-Erkennung sicher aus

      - name: ZIP als Artifact hochladen
        uses: actions/upload-artifact@v4
        with:
          name: ram-tool-mac
          path: frontend/release/*.zip   # Pfad ist relativ zum Repo-Root
